### PR TITLE
Added rsync install on Linux builds

### PR DESCRIPTION
**Pull request by radarhere**
While PR #77 is under development, here is a temporary fix for Issue #76.

I create this PR because I presume that a fix of some kind would be good before the next Pillow release.

### CODE REVIEW

**Comment by radarhere** [comment]
Inspired by https://github.com/matthew-brett/multibuild/commit/cba6a4228b28922799fde42e8a19833b81016816

**Comment by matthew-brett** [comment]
Just updating to the latest multibuild should fix it ...

**Comment by matthew-brett** [comment]
Does the compilation work when you use travis.yml to specify xcode 6.4?  Superficially it looks like the problem is from increased detail of clang checks.

**Comment by radarhere** [comment]
Yes - here is a Travis build - https://travis-ci.org/radarhere/pillow-wheels/builds/352232607 - with [the latest multibuild and Xcode 6.4](https://github.com/radarhere/pillow-wheels/commits/updated).

**Comment by matthew-brett** [comment]
How odd.  Just to be sure, I tried adding only the LIBRARY_PATH commit to your previous version of multibuild (and the rsync fix): https://travis-ci.org/matthew-brett/pillow-wheels/builds/352608508

**Comment by matthew-brett** [comment]
Hum - just adding that back replicated your error.  So, is this a clash between the already compiled libraries (now being found because of the include / library path setup) and libwebp, on modern clang?

**Comment by radarhere** [comment]
I have found that updating to Xcode 9.2 fixes this new problem. So I am closing this PR, and have instead created #79

**Pull request closed without merging**
