### PR TITLE
Upgraded numpy on 32-bit PyPy3.7 to match 64-bit

### PR DESCRIPTION
**Pull request by radarhere**
Simplifies code.

### CODE REVIEW

**Comment by hugovk** [comment]
What's the reason for pinning?

**Comment by radarhere** [comment]
I would say that it was already pinned, I'm just upgrading the pinned version.

If I [remove the pinning](https://github.com/radarhere/pillow-wheels/commit/5fb562313b166074b7bd503c6b744007a2cba0e6) for 32-bit, this is what happens - https://github.com/radarhere/pillow-wheels/runs/3521457144?check_suite_focus=true

**Comment by hugovk** [comment]
How does it look with `--only-binary=:all:`?

**Comment by radarhere** [comment]
https://github.com/radarhere/pillow-wheels/commit/0e9724d7cb803079e3c2b7c7473d1783d3c6db7b - [ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)](https://github.com/radarhere/pillow-wheels/runs/3521913853?check_suite_focus=true#step:4:6700)

**Comment by hugovk** [comment]
That's surprising! 

Thanks for trying the other options, let's keep the pin then :)

**Pull request merged**
