### PR TITLE
Removed Python 2 jobs

### PR DESCRIPTION
**Pull request by radarhere**
See https://github.com/python-pillow/Pillow/issues/3642

### CODE REVIEW

**Comment by hugovk** [comment]
If we merge this now, what would we need to do if we need to do a 6.2.x point release for Python 2.7?

Should we tag this master with `6.2.0` to match the main repo?

**Comment by radarhere** [comment]
I might have made a comment about point releases being rare, but then https://github.com/python-pillow/Pillow/issues/4110 suggested one, so never mind.

On the other hand, if PR https://github.com/python-pillow/Pillow/pull/4109 is merged, then the 2.7 wheels CI jobs will start failing.

**Comment by radarhere** [comment]
Actually, pillow-wheels 2.7 latest has already started failing - https://travis-ci.org/python-pillow/pillow-wheels/builds/602789711

**Comment by hugovk** [comment]
"Latest" is off the master branch, which no longer supports Python 2.7, right? 

If we needed to do a 6.2.2 security release for 2.7, that would be from the `6.2.x` branch and we don't need to worry about the latest (which happened with 6.2.1).

So we could exclude the 2.7/latest jobs here.

Or merge this, and if we do need to do a 6.2.2 (hopefully won't happen), we can always reinstate these 2.7 builds.

What do you think?

**Comment by radarhere** [comment]
We're now halfway towards the next release, and the odds of 6.2.2 gradually decrease as time goes on - we haven't made a patch release after the first month in the last three years.

I think it might be more valuable to merge, to allow better visibility for true failures. If 6.2.2 occurs, then we can work to involve 2.7 builds for that.

**Comment by hugovk** [comment]
Sounds good, thanks!

**Pull request merged**
