### PR TITLE
MRG: refactored repo to build manylinux1 wheels

### PR DESCRIPTION
**Pull request by matthew-brett**
Refactoring using `multibuild` submodule to run and test builds of manylinux1 wheels.

Builds and tests on 64- and 32-bit.

### CODE REVIEW

**Comment by aclark4life** [comment]
Hmmm, looks like Travis errors on this: https://travis-ci.org/python-pillow/pillow-wheels/builds/139092834

**Comment by hugovk** [comment]
@aclark4life Under discussion here: https://github.com/python-pillow/Pillow/issues/1973

**Comment by matthew-brett** [comment]
I put the 32-bit tests into the `allow_failure` for now.

Travis-ci is having trouble with its OSX VMs at the moment, so the OSX results may take a while to come through.

**Comment by AbdealiJK** [comment]
Could someone trigger a rebuild ? https://github.com/python-pillow/Pillow/pull/1990 should have fixed it

**Comment by wiredfool** [comment]
I've triggered a rebuild -- We should be able to drop the `allow_failure` on 32bit tests. Also, openjpeg should now work with the J2k patch that was just added.

**Comment by wiredfool** [comment]
That's not likely to work, I think we need to update the pointer to pillow as well, otherwise the rebuild isn't going to pull in the recent changes.

**Comment by matthew-brett** [comment]
Sure enough the 32-bit builds are still failing - see e.g https://travis-ci.org/matthew-brett/pillow-wheels/jobs/141333969.  This PR is building latest master, because it has `BUILD_COMMIT=master` in `.travis.yml` - see : https://travis-ci.org/matthew-brett/pillow-wheels/jobs/141333969#L228

**Comment by wiredfool** [comment]
Ok, checking.

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/1997 has been merged so I've restarted this build: https://travis-ci.org/python-pillow/pillow-wheels/builds/141333993

Assuming they pass, the `allow_failure` bit can be reverted.

**Comment by wiredfool** [comment]
Ok, didn't mean to close this.  github sometimes...

**Comment by wiredfool** [comment]
Looking good with the 32 bit builds.

**Comment by matthew-brett** [comment]
I removed `allow_failures` expecting everything to pass.

**Comment by AbdealiJK** [comment]
Awesome ! @wiredfool thank you for creating the extra commit to fix those 2 tests that I missed.

**Pull request merged**
