### PR TITLE
Added PyPy3.8

### PR DESCRIPTION
**Pull request by radarhere**
Added PyPy 3.8. I'm avoiding PyPy 3.9 for now, as it is in "beta".

This PR also updates to 7.3.8.

### CODE REVIEW

**Review by hugovk — APPROVED** [review]

**Comment by nulano** [comment]
> This PR also updates to 7.3.8.

From pypy-dev mailing list (emphasis mine):

> Once again, I broke ABI compatibility with the new release. I re-added
a field to PyDateTime_CAPI that should have been part of the original
PyPy3.7 release, but was missed, and so should be left out of PyPy3.7
v7.3.x. This causes segfaults when using PyPy3.7-v7.3.8 on wheels
built for PyPy3.7-v7.3.7 and older. **Please do not build packages with
PyPy3.7-v7.3.8 for general release because they will not work on older
PyPy3.7**.

>
> What is doubly annoying is this is exactly why I needed to release
v7.3.7 over v7.3.6. PRs welcome to suggest a test for this. A "hg
diff" is a start, but it picks up refactoring and valid additions as
well, so it needs to be a bit smarter. Maybe something with CFFI?

>
> Matti

**Comment by radarhere** [comment]
Thanks for the info.

Given that there was previous plan to release PyPy 7.3.9 almost a week ago,

https://libera.irclog.whitequark.org/pypy/2022-03-07
> it seems we should release 7.3.9 by March 14 to match CPython

I'm going to hold out hope that 7.3.9 will be released before April 1, so that we don't have to downgrade it for Pillow 9.1.0. Something to keep an eye on.

**Comment by hugovk** [comment]
https://libera.irclog.whitequark.org/pypy/search?q=7.3.9

Later 2022-03-09 messages say:

> [09:22](https://libera.irclog.whitequark.org/pypy/2022-03-09#31900569) <mattip> so it turns out we do not need a 7.3.9 for ABI compatibility,
> [09:22](https://libera.irclog.whitequark.org/pypy/2022-03-09#31900570) <mattip> PyO3 will reject 7.3.7 and earlier on py3.7 to work around the problem
> [09:23](https://libera.irclog.whitequark.org/pypy/2022-03-09#31900576) <mattip> we should still do a new release to build with pyexpat 2.4,7, bzip2 1.0.8, and sqlite 3.38
> [09:26](https://libera.irclog.whitequark.org/pypy/2022-03-09#31900592) <mattip> maybe it should be 7.3.8.final.1 ? Have we ever done a release with serial != 0?

Yesterday:

> [18:26](https://libera.irclog.whitequark.org/pypy/2022-03-19#31953836) <mattip> the 7.3.9 release is blocked by issue 3706: we need to refactor our headers to work with -Wstrict-aliasing

The release blocker: https://foss.heptapod.net/pypy/pypy/-/issues/3706

**Comment by radarhere** [comment]
PyPy 7.3.9 has now been merged in, with https://github.com/python-pillow/pillow-wheels/pull/272

**Pull request merged**
