### PR TITLE
Updated xz to 5.2.5

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by hugovk** [comment]
Hmm, CI didn't trigger, and nothing at https://travis-ci.org/github/python-pillow/pillow-wheels/pull_requests...

**Comment by radarhere** [comment]
Yes, my fork didn't trigger its CI either. I'm hoping it's just a temporary problem on the part of TravisCI.

**Comment by hugovk** [comment]
The Requests tab at https://travis-ci.org/github/python-pillow/pillow-wheels/requests shows "Build config did not create any jobs":

image

The same commit earlier did work on cron runs, but not now.

Travis recently-ish introduced build config validation:

https://docs.travis-ci.com/user/build-config-validation

Pasting `.travis.yml` into https://config.travis-ci.com/explore shows a couple of info messages, but no errors. However, the job matrix (scroll right) is `[]`...

**Comment by hugovk** [comment]
It's the combination of:

```yml
# Default Python version is usually 2.7
python: 3.5
```

And:

```yml
jobs:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
```

**Comment by hugovk** [comment]
Please see https://github.com/python-pillow/pillow-wheels/pull/142.

**Comment by hugovk** [comment]
There's an issue with macOS builds right now: https://www.traviscistatus.com/incidents/9861dc7dtsb0

**Comment by radarhere** [comment]
The incident link you've posted now says resolved, and the checks for this PR have all passed.

**Comment by hugovk** [comment]
Thanks!

**Pull request merged**
