### PR TITLE
[WIP] Add Python 3.7 to the travis builds.

### PR DESCRIPTION
**Pull request by jaraco**
I'm submitting this PR to see the effect of this change on the builds in Travis.

### CODE REVIEW

**Comment by radarhere** [comment]
https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions would indicate that there is no 3.7 on Travis at the moment, only 3.7-dev.

**Comment by hugovk** [comment]
Does it need adding to the multibuild repo first?

**Comment by matthew-brett** [comment]
Python 3.7 certainly does need adding to multibuild.  It's still at 3.7.0b4 : https://www.python.org/downloads/release/python-370b4 .  It doesn't look like it's reached the manylinux docker image yet.

**Comment by hugovk** [comment]
Here's the pending manylinux PR:
* https://github.com/pypa/manylinux/pull/196

**Comment by hugovk** [comment]
Manylinux has merged the PR and now has the latest 3.7.0rc1:

https://github.com/pypa/manylinux/pull/196

What's next? Can it be added to multibuild?

**Comment by hugovk** [comment]
Manylinux now has the newly released 3.7.0 final:

https://github.com/pypa/manylinux/pull/208

**Comment by hugovk** [comment]
Please see a continuation attempt in https://github.com/python-pillow/pillow-wheels/pull/90.

**Comment by hugovk** [comment]
Closing in favour of #90.

**Pull request closed without merging**
