### PR TITLE
Added Python 3.8

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by radarhere** [comment]
The [macOS install was failing](https://travis-ci.org/python-pillow/pillow-wheels/jobs/599032500#L101) because it was looking for 'python-3.8.0-macosx10.6.pkg' - which doesn't exist in https://www.python.org/ftp/python/3.8.0/. It looks like since https://www.python.org/ftp/python/3.7.5/, 10.6 has been dropped, leaving only 10.9. I updated the commit, and the builds now pass.

**Comment by hugovk** [comment]
Thanks!

Does that affect the minimum macOS we support?

**Comment by radarhere** [comment]
The deployment target for our builds is 10.10 - so we should be fine with installing a package for 10.9.

**Comment by hugovk** [comment]
Thank you!

**Pull request merged**
